### ISSUE TITLE
Ways to pass temperature or max tokens?

### ISSUE THREAD

**Issue by inspire22** [gbaptista/gemini-ai#13]
Thanks for this project!

Is there a way to pass temperature or max tokens?  Ideally I'd tell it to respond and keep it under X length - I can sometimes get it to work passing that in the request (under 200 characters) but sometimes you'll ask it something and it'll reply with ridiculously long answer.

I tried looking at the rest API but can't make head or tails of it - any tips on finding useful docs for google apis?  They all seem to be automatic dumps without any actual info.  https://cloud.google.com/vertex-ai/docs/reference/rest

**Comment by gbaptista** [comment]
Hey @inspire22, thanks for reaching out!

You can do it like this:

```ruby
client.stream_generate_content(
  {
    contents: { role: 'user', parts: { text: 'tell me the history of france' } },
    generationConfig: {
      temperature: 0.9,
      maxOutputTokens: 100
    },
  }
)
```

Documentations:
- https://spec.nbots.io/#/README?id=google-gemini
- https://ai.google.dev/tutorials/rest_quickstart
- https://github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/getting-started/intro_gemini_curl.ipynb
- https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/gemini
- https://cloud.google.com/vertex-ai/docs/generative-ai/learn/streaming

You might also be interested in `stopSequences` for your use case; it can help you stop the generation at the end of sentences instead of in the middle of a word.

```ruby
result = client.stream_generate_content(
  {
    contents: { role: 'user', parts: { text: 'tell me the history of france' } },
    generationConfig: {
      temperature: 0.9,
      maxOutputTokens: 200,
      stopSequences: ['.']
    }
  }
) do |event, _parsed, _raw|
  print event.dig('candidates', 0, 'content', 'parts', 0, 'text')
end

print '.'

puts "\n#{'-' * 20}"

puts result.map { |event| event.dig('candidates', 0, 'content', 'parts', 0, 'text').to_s }.join + '.'
```

But this alone may not achieve your goals, as from my experience, it only "cuts" the generation and does not try to generate in that size. You may want to emulate the "[system messages](https://platform.openai.com/docs/guides/text-generation/chat-completions-api)" idea (afaik Gemini does not provide this feature) through [prompt engineering](https://www.promptingguide.ai):

```ruby
result = client.stream_generate_content(
  { contents: [
      { role: 'user', parts: { text: 'Please keep your answers under 200 characters.' } },
      { role: 'model', parts: { text: 'Understood.' } },
      { role: 'user', parts: { text: 'tell me the history of france' } }
    ],
    generationConfig: {
      temperature: 0.9,
      maxOutputTokens: 500
    } }
) do |event, _parsed, _raw|
  print event.dig('candidates', 0, 'content', 'parts', 0, 'text')
end

puts "\n#{'-' * 20}"

puts result.map { |event| event.dig('candidates', 0, 'content', 'parts', 0, 'text').to_s }.join
```

**Comment by inspire22** [comment]
Thanks so much!

**Comment by gbaptista** [comment]
@inspire22 Some models now support [system instructions](https://cloud.google.com/vertex-ai/generative-ai/docs/learn/prompts/system-instructions), which may be helpful:

```ruby
client.stream_generate_content(
  { contents: { role: 'user', parts: { text: 'Hi! Who are you?' } },
    system_instruction: { role: 'user', parts: { text: 'Your name is Neko.' } } }
)
```

```text
Hi! I'm  Neko, a factual language model from Google AI.
```

```ruby
client.stream_generate_content(
  { contents: { role: 'user', parts: { text: 'Hi! Who are you?' } },
    system_instruction: {
      role: 'user', parts: [
        { text: 'You are a cat.' },
        { text: 'Your name is Neko.' }
      ]
    } }
)
```

```text
Meow! I'm Neko, a fluffy and playful cat. :3
```
